swagger: "2.0"
info:
  version: "1.0"
  title: Transport API 1.0
  description: |
  
    Endpoints exposed from the Core Serve - Transport path.
    
    Transport root Url https://mtv.musicqubed.com/transport/service/

    All endpoints have mandatory X-User-Agent HTTP Header.    

host: mtv.musicqubed.com
basePath: /transport/service/
schemes:
- https
consumes:
- application/json
produces:
- application/json
tags:
  - name: Installations
    description: |
      Defines set of endpoints required by application to complete installation and user identification flow. 
  - name: Products
    description: |
     Defines endpoints to manage product related information.
    

paths:
  /{community}/7.0/installations:
    post:
      description: |
        After new application installed/re-installed to a device, to complete installation proccess and register the installation with the server this request must be successful. It takes a JSON object containing a unique installationID (of the 128-bit UUID value) generated by application, unique deviceID and, optionally, push token of the specified push provider.Response provides details of success or failure (and reason).
  
      tags:
      - Installations
      produces:
      - application/json
      parameters:
      - name: community
        in: path
        required: true
        type: string
        description: Community name in the form of string
      - name: secureToken
        in: query
        required: true
        type: string
        description: Wiki page display/GINF/General defines how to generate one. Payload is installationID.
      - name: timestamp
        in: query
        required: true
        type: integer
        format: int64
        description: Wiki page describes why we need this.
      - name: body
        in: body
        required: true
        schema:
          type: object
          required:
          - installationID
          - deviceID
          properties:
            installationID:
              type: string
              example: de305d54-75b4-431b-adb2-eb6b9e546014
            deviceID:
              type: string
              example: client_format
            push:
              type: object
              description: Defines provider (as URBAN_AIRSHIP) & token to be used to push notifications back to the device.
              required:
              - providerType
              - token
              properties:
                providerType:
                  type: string
                  description: push provider name
                  example: URBAN_AIRSHIP
                token: 
                  type: string
                  description: push provider token
                  example: asdlkjlkj
          
      responses:
        201:
          description: (Created) is sent back in case of successully created resource with URI to the resource in Location Header to be used going forward.
          schema:
            type: object
            properties:
              installationID:
                description: installation UUID
                example: de305d54-75b4-431b-adb2-eb6b9e546014
                type: string
              installationToken:
                description: installation token
                example: value generated by server to be used in secureToken as payload going forward
                type: string
            required:
            - installationID
            - installationToken
        400:
          description: (Bad Request) is sent back in case of any issues while resolving parameters, headers or body elements.
        401:
          description: (Unauthorized) is sent back in case request failed to pass security context validations.
        404:
          description: (Not Found) is sent back in case there is either no requested community, apiVersion
        409:
          description: (Conflict) is sent back in case request from the client tries is the attempt to create duplicate installation resource (of the same installationID)
          

   